<h4>Done</h4>
<div id="other-messages" style="display:none;">
    <h4>Zendingen aangemaakt</h4>
    <p>Order overzicht kon niet ververst worden, aangemaakte zendingen pas zichtbaar na pagina refresh (F5).</p>
    <h4><a href="#" onclick="window.close(); return false;">Click here to close this window and return to webshop</a></h4>
</div>
<script type="text/javascript">
document.observe('dom:loaded', function(){
    if(!window.opener)
    {
        $('other-messages').show();
        return;
    }
    window.opener.sales_order_gridJsObject.doFilter();
    if('<?php echo $this->countConsignmentIds(); ?>' < window.opener.lastBatchCount)
    {
        alert('Door onvoldoende verzendrecht of onvolledige data slechts ' + <?php echo $this->countConsignmentIds(); ?> + ' van de ' + window.opener.lastBatchCount + ' zendingen aangemaakt. Verwerk de rest handmatig a.u.b.');
    }
    window.close();
});
</script>
